// Generated by CoffeeScript 1.6.3
var exports, fs, uniform;

require('js-yaml');

fs = require('fs');

uniform = function(spec) {
  var config;
  if (spec == null) {
    spec = null;
  }
  config;
  if (spec && spec.file && fs.existsSync(spec.file)) {
    config = require(spec.file);
  }
  if (config) {
    return console.log("config found");
  }
};

exports = uniform;
